version: "3"

services:
  cache:
    container_name: albion_cache
    network_mode: bridge
    ports:
      - "6379:6379"
    image: redis:latest
    volumes:
      - cache_data:/data

volumes:
  cache_data: